# Generated by Django 2.1.1 on 2018-09-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=12)),
                ('address', models.TextField()),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('phoneNumber', models.CharField(max_length=12)),
                ('cellPhoneNumber', models.CharField(max_length=12)),
            ],
        ),
    ]
