# Generated by Django 2.1.1 on 2018-09-24 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180923_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diner',
            name='user',
        ),
        migrations.RemoveField(
            model_name='healthcharacteristic',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='healthcharacteristic',
            name='user',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='user',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='user',
        ),
        migrations.DeleteModel(
            name='Diner',
        ),
        migrations.DeleteModel(
            name='HealthCharacteristic',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='Preference',
        ),
    ]
