# Generated by Django 2.1.1 on 2018-09-24 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20180923_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=9)),
                ('openningTime', models.TimeField()),
                ('clousingTime', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='manager',
        ),
        migrations.AddField(
            model_name='schedule',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
        ),
    ]
